// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/AboutView': RouteRecordInfo<'/AboutView', '/AboutView', Record<never, never>, Record<never, never>>,
    '/archive/academic-note/': RouteRecordInfo<'/archive/academic-note/', '/archive/academic-note', Record<never, never>, Record<never, never>>,
    '/archive/academic-note/view': RouteRecordInfo<'/archive/academic-note/view', '/archive/academic-note/view', Record<never, never>, Record<never, never>>,
    '/archive/academic-reference/': RouteRecordInfo<'/archive/academic-reference/', '/archive/academic-reference', Record<never, never>, Record<never, never>>,
    '/archive/academic-reference/create': RouteRecordInfo<'/archive/academic-reference/create', '/archive/academic-reference/create', Record<never, never>, Record<never, never>>,
    '/archive/academic-reference/id': RouteRecordInfo<'/archive/academic-reference/id', '/archive/academic-reference/id', Record<never, never>, Record<never, never>>,
    '/archive/accreditation/': RouteRecordInfo<'/archive/accreditation/', '/archive/accreditation', Record<never, never>, Record<never, never>>,
    '/archive/accreditation/id': RouteRecordInfo<'/archive/accreditation/id', '/archive/accreditation/id', Record<never, never>, Record<never, never>>,
    '/archive/certificate-committee/': RouteRecordInfo<'/archive/certificate-committee/', '/archive/certificate-committee', Record<never, never>, Record<never, never>>,
    '/archive/certificate-committee/certificate-committee-member': RouteRecordInfo<'/archive/certificate-committee/certificate-committee-member', '/archive/certificate-committee/certificate-committee-member', Record<never, never>, Record<never, never>>,
    '/archive/certificate-committee/create': RouteRecordInfo<'/archive/certificate-committee/create', '/archive/certificate-committee/create', Record<never, never>, Record<never, never>>,
    '/archive/certificate-committee/edit': RouteRecordInfo<'/archive/certificate-committee/edit', '/archive/certificate-committee/edit', Record<never, never>, Record<never, never>>,
    '/archive/circulation-sheet/': RouteRecordInfo<'/archive/circulation-sheet/', '/archive/circulation-sheet', Record<never, never>, Record<never, never>>,
    '/archive/circulation-sheet/removeCirculationSheet': RouteRecordInfo<'/archive/circulation-sheet/removeCirculationSheet', '/archive/circulation-sheet/removeCirculationSheet', Record<never, never>, Record<never, never>>,
    '/archive/circulation-sheet-check': RouteRecordInfo<'/archive/circulation-sheet-check', '/archive/circulation-sheet-check', Record<never, never>, Record<never, never>>,
    '/archive/diplom-ball/': RouteRecordInfo<'/archive/diplom-ball/', '/archive/diplom-ball', Record<never, never>, Record<never, never>>,
    '/archive/diplom-blank/': RouteRecordInfo<'/archive/diplom-blank/', '/archive/diplom-blank', Record<never, never>, Record<never, never>>,
    '/archive/diplom-give/': RouteRecordInfo<'/archive/diplom-give/', '/archive/diplom-give', Record<never, never>, Record<never, never>>,
    '/archive/diplom-give/create': RouteRecordInfo<'/archive/diplom-give/create', '/archive/diplom-give/create', Record<never, never>, Record<never, never>>,
    '/archive/diplom-give/edit': RouteRecordInfo<'/archive/diplom-give/edit', '/archive/diplom-give/edit', Record<never, never>, Record<never, never>>,
    '/archive/diplomaList': RouteRecordInfo<'/archive/diplomaList', '/archive/diplomaList', Record<never, never>, Record<never, never>>,
    '/archive/diplomas': RouteRecordInfo<'/archive/diplomas', '/archive/diplomas', Record<never, never>, Record<never, never>>,
    '/archive/employment/': RouteRecordInfo<'/archive/employment/', '/archive/employment', Record<never, never>, Record<never, never>>,
    '/archive/graduate-work/': RouteRecordInfo<'/archive/graduate-work/', '/archive/graduate-work', Record<never, never>, Record<never, never>>,
    '/archive/graduate-work/create': RouteRecordInfo<'/archive/graduate-work/create', '/archive/graduate-work/create', Record<never, never>, Record<never, never>>,
    '/archive/graduate-work/edit': RouteRecordInfo<'/archive/graduate-work/edit', '/archive/graduate-work/edit', Record<never, never>, Record<never, never>>,
    '/archive/reference/': RouteRecordInfo<'/archive/reference/', '/archive/reference', Record<never, never>, Record<never, never>>,
    '/archive/sheet/': RouteRecordInfo<'/archive/sheet/', '/archive/sheet', Record<never, never>, Record<never, never>>,
    '/archive/transcript/': RouteRecordInfo<'/archive/transcript/', '/archive/transcript', Record<never, never>, Record<never, never>>,
    '/archive/transcript/create': RouteRecordInfo<'/archive/transcript/create', '/archive/transcript/create', Record<never, never>, Record<never, never>>,
    '/archive/transcript/edit': RouteRecordInfo<'/archive/transcript/edit', '/archive/transcript/edit', Record<never, never>, Record<never, never>>,
    '/attendance/attendance-setting/': RouteRecordInfo<'/attendance/attendance-setting/', '/attendance/attendance-setting', Record<never, never>, Record<never, never>>,
    '/attendance/journal/': RouteRecordInfo<'/attendance/journal/', '/attendance/journal', Record<never, never>, Record<never, never>>,
    '/attendance/journal/id': RouteRecordInfo<'/attendance/journal/id', '/attendance/journal/id', Record<never, never>, Record<never, never>>,
    '/attendance/lessons/': RouteRecordInfo<'/attendance/lessons/', '/attendance/lessons', Record<never, never>, Record<never, never>>,
    '/attendance/report': RouteRecordInfo<'/attendance/report', '/attendance/report', Record<never, never>, Record<never, never>>,
    '/attendance/statistic': RouteRecordInfo<'/attendance/statistic', '/attendance/statistic', Record<never, never>, Record<never, never>>,
    '/attendance/status': RouteRecordInfo<'/attendance/status', '/attendance/status', Record<never, never>, Record<never, never>>,
    '/attendance/subject': RouteRecordInfo<'/attendance/subject', '/attendance/subject', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/career/': RouteRecordInfo<'/career/', '/career', Record<never, never>, Record<never, never>>,
    '/career/crud': RouteRecordInfo<'/career/crud', '/career/crud', Record<never, never>, Record<never, never>>,
    '/conferences/': RouteRecordInfo<'/conferences/', '/conferences', Record<never, never>, Record<never, never>>,
    '/conferences/view': RouteRecordInfo<'/conferences/view', '/conferences/view', Record<never, never>, Record<never, never>>,
    '/coordinator/all-group/': RouteRecordInfo<'/coordinator/all-group/', '/coordinator/all-group', Record<never, never>, Record<never, never>>,
    '/coordinator/group-coordinator/': RouteRecordInfo<'/coordinator/group-coordinator/', '/coordinator/group-coordinator', Record<never, never>, Record<never, never>>,
    '/coordinator/group-coordinator/id': RouteRecordInfo<'/coordinator/group-coordinator/id', '/coordinator/group-coordinator/id', Record<never, never>, Record<never, never>>,
    '/coordinator/list-coordinator/': RouteRecordInfo<'/coordinator/list-coordinator/', '/coordinator/list-coordinator', Record<never, never>, Record<never, never>>,
    '/coordinator/list-coordinator/id': RouteRecordInfo<'/coordinator/list-coordinator/id', '/coordinator/list-coordinator/id', Record<never, never>, Record<never, never>>,
    '/curriculum/curriculum/': RouteRecordInfo<'/curriculum/curriculum/', '/curriculum/curriculum', Record<never, never>, Record<never, never>>,
    '/curriculum/curriculum/[id]/': RouteRecordInfo<'/curriculum/curriculum/[id]/', '/curriculum/curriculum/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/curriculum/[id]/create-subject': RouteRecordInfo<'/curriculum/curriculum/[id]/create-subject', '/curriculum/curriculum/:id/create-subject', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/curriculum/[id]/subject-update': RouteRecordInfo<'/curriculum/curriculum/[id]/subject-update', '/curriculum/curriculum/:id/subject-update', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/curriculum/[id]/subjects': RouteRecordInfo<'/curriculum/curriculum/[id]/subjects', '/curriculum/curriculum/:id/subjects', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/curriculum/[id]/week': RouteRecordInfo<'/curriculum/curriculum/[id]/week', '/curriculum/curriculum/:id/week', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/curriculum/create': RouteRecordInfo<'/curriculum/curriculum/create', '/curriculum/curriculum/create', Record<never, never>, Record<never, never>>,
    '/curriculum/curriculum-archive/': RouteRecordInfo<'/curriculum/curriculum-archive/', '/curriculum/curriculum-archive', Record<never, never>, Record<never, never>>,
    '/curriculum/curriculum-list/': RouteRecordInfo<'/curriculum/curriculum-list/', '/curriculum/curriculum-list', Record<never, never>, Record<never, never>>,
    '/curriculum/curriculum-list/curriculum': RouteRecordInfo<'/curriculum/curriculum-list/curriculum', '/curriculum/curriculum-list/curriculum', Record<never, never>, Record<never, never>>,
    '/curriculum/education-year/': RouteRecordInfo<'/curriculum/education-year/', '/curriculum/education-year', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/': RouteRecordInfo<'/curriculum/exam/', '/curriculum/exam', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/create': RouteRecordInfo<'/curriculum/exam/create', '/curriculum/exam/create', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/questions': RouteRecordInfo<'/curriculum/exam/questions', '/curriculum/exam/questions', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/questionsInput': RouteRecordInfo<'/curriculum/exam/questionsInput', '/curriculum/exam/questionsInput', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/result': RouteRecordInfo<'/curriculum/exam/result', '/curriculum/exam/result', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/resultStudent': RouteRecordInfo<'/curriculum/exam/resultStudent', '/curriculum/exam/resultStudent', Record<never, never>, Record<never, never>>,
    '/curriculum/exam/subject': RouteRecordInfo<'/curriculum/exam/subject', '/curriculum/exam/subject', Record<never, never>, Record<never, never>>,
    '/curriculum/exam-list/': RouteRecordInfo<'/curriculum/exam-list/', '/curriculum/exam-list', Record<never, never>, Record<never, never>>,
    '/curriculum/exam-list/exam': RouteRecordInfo<'/curriculum/exam-list/exam', '/curriculum/exam-list/exam', Record<never, never>, Record<never, never>>,
    '/curriculum/exam-schedule/': RouteRecordInfo<'/curriculum/exam-schedule/', '/curriculum/exam-schedule', Record<never, never>, Record<never, never>>,
    '/curriculum/exam-schedule/[id]/': RouteRecordInfo<'/curriculum/exam-schedule/[id]/', '/curriculum/exam-schedule/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/grade-type/': RouteRecordInfo<'/curriculum/grade-type/', '/curriculum/grade-type', Record<never, never>, Record<never, never>>,
    '/curriculum/info-schedule/': RouteRecordInfo<'/curriculum/info-schedule/', '/curriculum/info-schedule', Record<never, never>, Record<never, never>>,
    '/curriculum/info-schedule/[id]/': RouteRecordInfo<'/curriculum/info-schedule/[id]/', '/curriculum/info-schedule/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/curriculum/info-schedule/generation': RouteRecordInfo<'/curriculum/info-schedule/generation', '/curriculum/info-schedule/generation', Record<never, never>, Record<never, never>>,
    '/curriculum/lesson-pair/': RouteRecordInfo<'/curriculum/lesson-pair/', '/curriculum/lesson-pair', Record<never, never>, Record<never, never>>,
    '/curriculum/marking-system/': RouteRecordInfo<'/curriculum/marking-system/', '/curriculum/marking-system', Record<never, never>, Record<never, never>>,
    '/curriculum/rating-grade/': RouteRecordInfo<'/curriculum/rating-grade/', '/curriculum/rating-grade', Record<never, never>, Record<never, never>>,
    '/curriculum/schedule-exam/': RouteRecordInfo<'/curriculum/schedule-exam/', '/curriculum/schedule-exam', Record<never, never>, Record<never, never>>,
    '/curriculum/schedule-exam/exam': RouteRecordInfo<'/curriculum/schedule-exam/exam', '/curriculum/schedule-exam/exam', Record<never, never>, Record<never, never>>,
    '/curriculum/schedule-list/': RouteRecordInfo<'/curriculum/schedule-list/', '/curriculum/schedule-list', Record<never, never>, Record<never, never>>,
    '/curriculum/schedule-list/schedule': RouteRecordInfo<'/curriculum/schedule-list/schedule', '/curriculum/schedule-list/schedule', Record<never, never>, Record<never, never>>,
    '/curriculum/semester/': RouteRecordInfo<'/curriculum/semester/', '/curriculum/semester', Record<never, never>, Record<never, never>>,
    '/curriculum/student-register': RouteRecordInfo<'/curriculum/student-register', '/curriculum/student-register', Record<never, never>, Record<never, never>>,
    '/employee/advenced-training/': RouteRecordInfo<'/employee/advenced-training/', '/employee/advenced-training', Record<never, never>, Record<never, never>>,
    '/employee/advenced-training/monitoring': RouteRecordInfo<'/employee/advenced-training/monitoring', '/employee/advenced-training/monitoring', Record<never, never>, Record<never, never>>,
    '/employee/employee-competition/': RouteRecordInfo<'/employee/employee-competition/', '/employee/employee-competition', Record<never, never>, Record<never, never>>,
    '/employee/employee-competition/monitoring': RouteRecordInfo<'/employee/employee-competition/monitoring', '/employee/employee-competition/monitoring', Record<never, never>, Record<never, never>>,
    '/employee/teacher/': RouteRecordInfo<'/employee/teacher/', '/employee/teacher', Record<never, never>, Record<never, never>>,
    '/employee/tyutor/': RouteRecordInfo<'/employee/tyutor/', '/employee/tyutor', Record<never, never>, Record<never, never>>,
    '/employee/tyutor/id': RouteRecordInfo<'/employee/tyutor/id', '/employee/tyutor/id', Record<never, never>, Record<never, never>>,
    '/employee-information/employee-data/': RouteRecordInfo<'/employee-information/employee-data/', '/employee-information/employee-data', Record<never, never>, Record<never, never>>,
    '/employee-information/employee-data/employee/[id]': RouteRecordInfo<'/employee-information/employee-data/employee/[id]', '/employee-information/employee-data/employee/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/employee-information/employee-list/': RouteRecordInfo<'/employee-information/employee-list/', '/employee-information/employee-list', Record<never, never>, Record<never, never>>,
    '/employee-information/employee-status/': RouteRecordInfo<'/employee-information/employee-status/', '/employee-information/employee-status', Record<never, never>, Record<never, never>>,
    '/employee-information/foreign-professor': RouteRecordInfo<'/employee-information/foreign-professor', '/employee-information/foreign-professor', Record<never, never>, Record<never, never>>,
    '/employee-information/foreign-training/': RouteRecordInfo<'/employee-information/foreign-training/', '/employee-information/foreign-training', Record<never, never>, Record<never, never>>,
    '/employee-information/scientific-status/': RouteRecordInfo<'/employee-information/scientific-status/', '/employee-information/scientific-status', Record<never, never>, Record<never, never>>,
    '/employee-information/teacher-list/': RouteRecordInfo<'/employee-information/teacher-list/', '/employee-information/teacher-list', Record<never, never>, Record<never, never>>,
    '/finance/contract': RouteRecordInfo<'/finance/contract', '/finance/contract', Record<never, never>, Record<never, never>>,
    '/finance/stipend/id': RouteRecordInfo<'/finance/stipend/id', '/finance/stipend/id', Record<never, never>, Record<never, never>>,
    '/finance/stipend/stipend': RouteRecordInfo<'/finance/stipend/stipend', '/finance/stipend/stipend', Record<never, never>, Record<never, never>>,
    '/finance/stipend/stipend-set': RouteRecordInfo<'/finance/stipend/stipend-set', '/finance/stipend/stipend-set', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/icons/fontawesome': RouteRecordInfo<'/icons/fontawesome', '/icons/fontawesome', Record<never, never>, Record<never, never>>,
    '/infrastructure/auditorium/': RouteRecordInfo<'/infrastructure/auditorium/', '/infrastructure/auditorium', Record<never, never>, Record<never, never>>,
    '/infrastructure/building/': RouteRecordInfo<'/infrastructure/building/', '/infrastructure/building', Record<never, never>, Record<never, never>>,
    '/invoices/detail': RouteRecordInfo<'/invoices/detail', '/invoices/detail', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/messages/': RouteRecordInfo<'/messages/', '/messages', Record<never, never>, Record<never, never>>,
    '/messages/[id]': RouteRecordInfo<'/messages/[id]', '/messages/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/messages/compose': RouteRecordInfo<'/messages/compose', '/messages/compose', Record<never, never>, Record<never, never>>,
    '/my-profil': RouteRecordInfo<'/my-profil', '/my-profil', Record<never, never>, Record<never, never>>,
    '/performance/debtors/': RouteRecordInfo<'/performance/debtors/', '/performance/debtors', Record<never, never>, Record<never, never>>,
    '/performance/debtors/exam': RouteRecordInfo<'/performance/debtors/exam', '/performance/debtors/exam', Record<never, never>, Record<never, never>>,
    '/performance/gpa/': RouteRecordInfo<'/performance/gpa/', '/performance/gpa', Record<never, never>, Record<never, never>>,
    '/performance/gpa/exam': RouteRecordInfo<'/performance/gpa/exam', '/performance/gpa/exam', Record<never, never>, Record<never, never>>,
    '/performance/gpa/gpa-add': RouteRecordInfo<'/performance/gpa/gpa-add', '/performance/gpa/gpa-add', Record<never, never>, Record<never, never>>,
    '/performance/graphic/': RouteRecordInfo<'/performance/graphic/', '/performance/graphic', Record<never, never>, Record<never, never>>,
    '/performance/graphic/add': RouteRecordInfo<'/performance/graphic/add', '/performance/graphic/add', Record<never, never>, Record<never, never>>,
    '/performance/graphic/create': RouteRecordInfo<'/performance/graphic/create', '/performance/graphic/create', Record<never, never>, Record<never, never>>,
    '/performance/graphic/id': RouteRecordInfo<'/performance/graphic/id', '/performance/graphic/id', Record<never, never>, Record<never, never>>,
    '/performance/performance/': RouteRecordInfo<'/performance/performance/', '/performance/performance', Record<never, never>, Record<never, never>>,
    '/performance/performance/id': RouteRecordInfo<'/performance/performance/id', '/performance/performance/id', Record<never, never>, Record<never, never>>,
    '/performance/student-information/academic-groups/': RouteRecordInfo<'/performance/student-information/academic-groups/', '/performance/student-information/academic-groups', Record<never, never>, Record<never, never>>,
    '/performance/student-information/contingent-list/': RouteRecordInfo<'/performance/student-information/contingent-list/', '/performance/student-information/contingent-list', Record<never, never>, Record<never, never>>,
    '/performance/student-information/student-data/': RouteRecordInfo<'/performance/student-information/student-data/', '/performance/student-information/student-data', Record<never, never>, Record<never, never>>,
    '/performance/student-information/student-data/createStudent': RouteRecordInfo<'/performance/student-information/student-data/createStudent', '/performance/student-information/student-data/createStudent', Record<never, never>, Record<never, never>>,
    '/performance/student-information/student-list/': RouteRecordInfo<'/performance/student-information/student-list/', '/performance/student-information/student-list', Record<never, never>, Record<never, never>>,
    '/performance/summary': RouteRecordInfo<'/performance/summary', '/performance/summary', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/report/by-exam/': RouteRecordInfo<'/report/by-exam/', '/report/by-exam', Record<never, never>, Record<never, never>>,
    '/report/by-resources/': RouteRecordInfo<'/report/by-resources/', '/report/by-resources', Record<never, never>, Record<never, never>>,
    '/report/by-rooms/': RouteRecordInfo<'/report/by-rooms/', '/report/by-rooms', Record<never, never>, Record<never, never>>,
    '/report/by-student/': RouteRecordInfo<'/report/by-student/', '/report/by-student', Record<never, never>, Record<never, never>>,
    '/report/by-teacher/': RouteRecordInfo<'/report/by-teacher/', '/report/by-teacher', Record<never, never>, Record<never, never>>,
    '/report/teacher-map/': RouteRecordInfo<'/report/teacher-map/', '/report/teacher-map', Record<never, never>, Record<never, never>>,
    '/science/department-rating/': RouteRecordInfo<'/science/department-rating/', '/science/department-rating', Record<never, never>, Record<never, never>>,
    '/science/teacher-rating/': RouteRecordInfo<'/science/teacher-rating/', '/science/teacher-rating', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-methodical/': RouteRecordInfo<'/scientific-activity/publication-methodical/', '/scientific-activity/publication-methodical', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-methodical/add': RouteRecordInfo<'/scientific-activity/publication-methodical/add', '/scientific-activity/publication-methodical/add', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-methodical/id': RouteRecordInfo<'/scientific-activity/publication-methodical/id', '/scientific-activity/publication-methodical/id', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-methodical-check/': RouteRecordInfo<'/scientific-activity/publication-methodical-check/', '/scientific-activity/publication-methodical-check', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-property/': RouteRecordInfo<'/scientific-activity/publication-property/', '/scientific-activity/publication-property', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-property/add': RouteRecordInfo<'/scientific-activity/publication-property/add', '/scientific-activity/publication-property/add', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-property/id': RouteRecordInfo<'/scientific-activity/publication-property/id', '/scientific-activity/publication-property/id', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-property-check/': RouteRecordInfo<'/scientific-activity/publication-property-check/', '/scientific-activity/publication-property-check', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-scientifical/': RouteRecordInfo<'/scientific-activity/publication-scientifical/', '/scientific-activity/publication-scientifical', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-scientifical/add': RouteRecordInfo<'/scientific-activity/publication-scientifical/add', '/scientific-activity/publication-scientifical/add', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-scientifical/id': RouteRecordInfo<'/scientific-activity/publication-scientifical/id', '/scientific-activity/publication-scientifical/id', Record<never, never>, Record<never, never>>,
    '/scientific-activity/publication-scientifical-check/': RouteRecordInfo<'/scientific-activity/publication-scientifical-check/', '/scientific-activity/publication-scientifical-check', Record<never, never>, Record<never, never>>,
    '/scientific-activity/scientific-activity/': RouteRecordInfo<'/scientific-activity/scientific-activity/', '/scientific-activity/scientific-activity', Record<never, never>, Record<never, never>>,
    '/scientific-activity/scientific-activity-check/': RouteRecordInfo<'/scientific-activity/scientific-activity-check/', '/scientific-activity/scientific-activity-check', Record<never, never>, Record<never, never>>,
    '/statistical/all-contract/': RouteRecordInfo<'/statistical/all-contract/', '/statistical/all-contract', Record<never, never>, Record<never, never>>,
    '/statistical/by-contract/': RouteRecordInfo<'/statistical/by-contract/', '/statistical/by-contract', Record<never, never>, Record<never, never>>,
    '/statistical/by-employment/': RouteRecordInfo<'/statistical/by-employment/', '/statistical/by-employment', Record<never, never>, Record<never, never>>,
    '/statistical/by-performance/': RouteRecordInfo<'/statistical/by-performance/', '/statistical/by-performance', Record<never, never>, Record<never, never>>,
    '/statistical/by-student/': RouteRecordInfo<'/statistical/by-student/', '/statistical/by-student', Record<never, never>, Record<never, never>>,
    '/statistical/by-student/all': RouteRecordInfo<'/statistical/by-student/all', '/statistical/by-student/all', Record<never, never>, Record<never, never>>,
    '/statistical/by-student-general/': RouteRecordInfo<'/statistical/by-student-general/', '/statistical/by-student-general', Record<never, never>, Record<never, never>>,
    '/statistical/by-student-social/': RouteRecordInfo<'/statistical/by-student-social/', '/statistical/by-student-social', Record<never, never>, Record<never, never>>,
    '/statistical/by-teacher/': RouteRecordInfo<'/statistical/by-teacher/', '/statistical/by-teacher', Record<never, never>, Record<never, never>>,
    '/statistical/by-training/': RouteRecordInfo<'/statistical/by-training/', '/statistical/by-training', Record<never, never>, Record<never, never>>,
    '/statistical/resource-statistics/': RouteRecordInfo<'/statistical/resource-statistics/', '/statistical/resource-statistics', Record<never, never>, Record<never, never>>,
    '/status-student/order-list/': RouteRecordInfo<'/status-student/order-list/', '/status-student/order-list', Record<never, never>, Record<never, never>>,
    '/status-student/order-list/[id]/': RouteRecordInfo<'/status-student/order-list/[id]/', '/status-student/order-list/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/status-student/order-list/apply-order': RouteRecordInfo<'/status-student/order-list/apply-order', '/status-student/order-list/apply-order', Record<never, never>, Record<never, never>>,
    '/status-student/order-list/create-order': RouteRecordInfo<'/status-student/order-list/create-order', '/status-student/order-list/create-order', Record<never, never>, Record<never, never>>,
    '/status-student/status': RouteRecordInfo<'/status-student/status', '/status-student/status', Record<never, never>, Record<never, never>>,
    '/status-student/student-transfer/': RouteRecordInfo<'/status-student/student-transfer/', '/status-student/student-transfer', Record<never, never>, Record<never, never>>,
    '/status-student/student-transfer/semestr': RouteRecordInfo<'/status-student/student-transfer/semestr', '/status-student/student-transfer/semestr', Record<never, never>, Record<never, never>>,
    '/status-student/timetable': RouteRecordInfo<'/status-student/timetable', '/status-student/timetable', Record<never, never>, Record<never, never>>,
    '/status-student/timetable2': RouteRecordInfo<'/status-student/timetable2', '/status-student/timetable2', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-course': RouteRecordInfo<'/status-student/transfer-course', '/status-student/transfer-course', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-course-down': RouteRecordInfo<'/status-student/transfer-course-down', '/status-student/transfer-course-down', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-finish': RouteRecordInfo<'/status-student/transfer-finish', '/status-student/transfer-finish', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-mobile': RouteRecordInfo<'/status-student/transfer-mobile', '/status-student/transfer-mobile', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-out': RouteRecordInfo<'/status-student/transfer-out', '/status-student/transfer-out', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-recovery/': RouteRecordInfo<'/status-student/transfer-recovery/', '/status-student/transfer-recovery', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-recovery/components/nested': RouteRecordInfo<'/status-student/transfer-recovery/components/nested', '/status-student/transfer-recovery/components/nested', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-recovery/id': RouteRecordInfo<'/status-student/transfer-recovery/id', '/status-student/transfer-recovery/id', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-recovery/test': RouteRecordInfo<'/status-student/transfer-recovery/test', '/status-student/transfer-recovery/test', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-return': RouteRecordInfo<'/status-student/transfer-return', '/status-student/transfer-return', Record<never, never>, Record<never, never>>,
    '/status-student/transfer-vacation': RouteRecordInfo<'/status-student/transfer-vacation', '/status-student/transfer-vacation', Record<never, never>, Record<never, never>>,
    '/structure/department/': RouteRecordInfo<'/structure/department/', '/structure/department', Record<never, never>, Record<never, never>>,
    '/structure/department_shablon/': RouteRecordInfo<'/structure/department_shablon/', '/structure/department_shablon', Record<never, never>, Record<never, never>>,
    '/structure/faculty/': RouteRecordInfo<'/structure/faculty/', '/structure/faculty', Record<never, never>, Record<never, never>>,
    '/structure/section/': RouteRecordInfo<'/structure/section/', '/structure/section', Record<never, never>, Record<never, never>>,
    '/structure/university/': RouteRecordInfo<'/structure/university/', '/structure/university', Record<never, never>, Record<never, never>>,
    '/student/attach': RouteRecordInfo<'/student/attach', '/student/attach', Record<never, never>, Record<never, never>>,
    '/student/award/': RouteRecordInfo<'/student/award/', '/student/award', Record<never, never>, Record<never, never>>,
    '/student/award/create': RouteRecordInfo<'/student/award/create', '/student/award/create', Record<never, never>, Record<never, never>>,
    '/student/qualification/': RouteRecordInfo<'/student/qualification/', '/student/qualification', Record<never, never>, Record<never, never>>,
    '/student/qualification/creat': RouteRecordInfo<'/student/qualification/creat', '/student/qualification/creat', Record<never, never>, Record<never, never>>,
    '/student/special/': RouteRecordInfo<'/student/special/', '/student/special', Record<never, never>, Record<never, never>>,
    '/student/student/': RouteRecordInfo<'/student/student/', '/student/student', Record<never, never>, Record<never, never>>,
    '/student/student/[id]/': RouteRecordInfo<'/student/student/[id]/', '/student/student/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/student/student/create': RouteRecordInfo<'/student/student/create', '/student/student/create', Record<never, never>, Record<never, never>>,
    '/student/student-list/': RouteRecordInfo<'/student/student-list/', '/student/student-list', Record<never, never>, Record<never, never>>,
    '/subjects/calendar-plan/': RouteRecordInfo<'/subjects/calendar-plan/', '/subjects/calendar-plan', Record<never, never>, Record<never, never>>,
    '/subjects/calendar-plan/id': RouteRecordInfo<'/subjects/calendar-plan/id', '/subjects/calendar-plan/id', Record<never, never>, Record<never, never>>,
    '/system/admin/': RouteRecordInfo<'/system/admin/', '/system/admin', Record<never, never>, Record<never, never>>,
    '/system/admin/create': RouteRecordInfo<'/system/admin/create', '/system/admin/create', Record<never, never>, Record<never, never>>,
    '/system/backup': RouteRecordInfo<'/system/backup', '/system/backup', Record<never, never>, Record<never, never>>,
    '/system/configuration': RouteRecordInfo<'/system/configuration', '/system/configuration', Record<never, never>, Record<never, never>>,
    '/system/login': RouteRecordInfo<'/system/login', '/system/login', Record<never, never>, Record<never, never>>,
    '/system/manager': RouteRecordInfo<'/system/manager', '/system/manager', Record<never, never>, Record<never, never>>,
    '/system/role/': RouteRecordInfo<'/system/role/', '/system/role', Record<never, never>, Record<never, never>>,
    '/system/role/role-edit': RouteRecordInfo<'/system/role/role-edit', '/system/role/role-edit', Record<never, never>, Record<never, never>>,
    '/system/role/roles': RouteRecordInfo<'/system/role/roles', '/system/role/roles', Record<never, never>, Record<never, never>>,
    '/system/system-log/': RouteRecordInfo<'/system/system-log/', '/system/system-log', Record<never, never>, Record<never, never>>,
    '/system/system-log/id': RouteRecordInfo<'/system/system-log/id', '/system/system-log/id', Record<never, never>, Record<never, never>>,
    '/teacher/attendance-journal/': RouteRecordInfo<'/teacher/attendance-journal/', '/teacher/attendance-journal', Record<never, never>, Record<never, never>>,
    '/teacher/attendance-journal/check-lesson': RouteRecordInfo<'/teacher/attendance-journal/check-lesson', '/teacher/attendance-journal/check-lesson', Record<never, never>, Record<never, never>>,
    '/teacher/attendance-journal/journal': RouteRecordInfo<'/teacher/attendance-journal/journal', '/teacher/attendance-journal/journal', Record<never, never>, Record<never, never>>,
    '/teacher/certificate-committee-result/': RouteRecordInfo<'/teacher/certificate-committee-result/', '/teacher/certificate-committee-result', Record<never, never>, Record<never, never>>,
    '/teacher/certificate-committee-result/[id]/': RouteRecordInfo<'/teacher/certificate-committee-result/[id]/', '/teacher/certificate-committee-result/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/teacher/certificate-committee-result/create': RouteRecordInfo<'/teacher/certificate-committee-result/create', '/teacher/certificate-committee-result/create', Record<never, never>, Record<never, never>>,
    '/teacher/final-exam-table/': RouteRecordInfo<'/teacher/final-exam-table/', '/teacher/final-exam-table', Record<never, never>, Record<never, never>>,
    '/teacher/final-exam-table/check-lesson': RouteRecordInfo<'/teacher/final-exam-table/check-lesson', '/teacher/final-exam-table/check-lesson', Record<never, never>, Record<never, never>>,
    '/teacher/midterm-exam-table/': RouteRecordInfo<'/teacher/midterm-exam-table/', '/teacher/midterm-exam-table', Record<never, never>, Record<never, never>>,
    '/teacher/midterm-exam-table/check-lesson': RouteRecordInfo<'/teacher/midterm-exam-table/check-lesson', '/teacher/midterm-exam-table/check-lesson', Record<never, never>, Record<never, never>>,
    '/teacher/other-exam-table/': RouteRecordInfo<'/teacher/other-exam-table/', '/teacher/other-exam-table', Record<never, never>, Record<never, never>>,
    '/teacher/other-exam-table/check-lesson': RouteRecordInfo<'/teacher/other-exam-table/check-lesson', '/teacher/other-exam-table/check-lesson', Record<never, never>, Record<never, never>>,
    '/teacher/rating-journal/': RouteRecordInfo<'/teacher/rating-journal/', '/teacher/rating-journal', Record<never, never>, Record<never, never>>,
    '/teacher/rating-journal/check-lesson': RouteRecordInfo<'/teacher/rating-journal/check-lesson', '/teacher/rating-journal/check-lesson', Record<never, never>, Record<never, never>>,
    '/teacher/rating-journal/journal': RouteRecordInfo<'/teacher/rating-journal/journal', '/teacher/rating-journal/journal', Record<never, never>, Record<never, never>>,
    '/teacher/time-table/': RouteRecordInfo<'/teacher/time-table/', '/teacher/time-table', Record<never, never>, Record<never, never>>,
    '/teacher/time-table/check-lesson': RouteRecordInfo<'/teacher/time-table/check-lesson', '/teacher/time-table/check-lesson', Record<never, never>, Record<never, never>>,
    '/teacher/training-list/': RouteRecordInfo<'/teacher/training-list/', '/teacher/training-list', Record<never, never>, Record<never, never>>,
    '/teacher/training-list/check-lesson': RouteRecordInfo<'/teacher/training-list/check-lesson', '/teacher/training-list/check-lesson', Record<never, never>, Record<never, never>>,
    '/utility/404': RouteRecordInfo<'/utility/404', '/utility/404', Record<never, never>, Record<never, never>>,
    '/utility/500': RouteRecordInfo<'/utility/500', '/utility/500', Record<never, never>, Record<never, never>>,
    '/utility/coming-soon': RouteRecordInfo<'/utility/coming-soon', '/utility/coming-soon', Record<never, never>, Record<never, never>>,
    '/utility/faqs': RouteRecordInfo<'/utility/faqs', '/utility/faqs', Record<never, never>, Record<never, never>>,
    '/utility/maintenance': RouteRecordInfo<'/utility/maintenance', '/utility/maintenance', Record<never, never>, Record<never, never>>,
    '/utility/pricing': RouteRecordInfo<'/utility/pricing', '/utility/pricing', Record<never, never>, Record<never, never>>,
    '/utility/starter': RouteRecordInfo<'/utility/starter', '/utility/starter', Record<never, never>, Record<never, never>>,
    '/utility/timeline': RouteRecordInfo<'/utility/timeline', '/utility/timeline', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
